dataset:
  name: "brain_mri"

  raw_dir: "data/raw/brain_mri/Training"
  test_dir: "data/raw/brain_mri/Testing"

  image_size: [224, 224]
  batch_size: 32
  validation_split: 0.1
  seed: 123

augmentation:
  enabled: true

  rotation: 0.02
  width_shift: 0.05
  height_shift: 0.05
  zoom: 0.05
  horizontal_flip: false
  brightness_range: false
  contrast: false
  random_crop: false

model:
  architecture: "xception"
  pretrained_weights: "imagenet"

  trainable_layers: 0

  dense_units_1: 256
  dropout_1: 0.3
  dense_units_2: 128
  dropout_2: 0.3

  output_classes: 4
  output_activation: "softmax"

training:
  optimizer: "adam"
  learning_rate: 0.0005
  epochs: 30
  early_stopping_patience: 5

  lr_scheduler: true
  reduce_lr_factor: 0.3
  reduce_lr_patience: 2

paths:
  model_dir: "models/brain_mri"
  model_filename: "brain_mri_efficientnetb0"   # SavedModel folder name
  mlflow_experiment: "BrainMRI_Training"

logging:
  mlflow_tracking_uri: "file:./mlruns"

fine_tuning:
  enabled: true
  unfreeze_after_epochs: 5
  trainable_layers: 40

class_weights:
  enabled: true
